### ISSUE TITLE
Null Reference Exceptions in GetMetaDataAsync

### ISSUE THREAD

**Issue by hartez** [hartez/TodotxtTouch.WindowsPhone#7]
Version 1.0.5.0
NullReferenceException
   at TodotxtTouch.WindowsPhone.Service.DropboxService.<>c__DisplayClass5.<WrapExceptionHandler>b__4(DropboxException ex)
   at DropNet.DropNetClient.ExecuteAsync[T](ApiType apiType, RestRequest request, Action`1 success, Action`1 failure)
   at DropNet.DropNetClient.GetMetaDataAsync(String path, Action`1 success, Action`1 failure)
   at TodotxtTouch.WindowsPhone.Service.DropboxService.<>c__DisplayClass8.<GetMetaData>b__7()
   at TodotxtTouch.WindowsPhone.Service.DropboxService.ExecuteDropboxAction(Action dropboxAction)
   at TodotxtTouch.WindowsPhone.Service.DropboxService.GetMetaData(String path, Action`1 success, Action`1 failure)
   at TodotxtTouch.WindowsPhone.Service.TaskFileService.GetRemoteMetaData(Action`1 success, Action`1 failure)
   at TodotxtTouch.WindowsPhone.Service.TaskFileService.Sync()
   at TodotxtTouch.WindowsPhone.ViewModel.MainViewModel.Sync()
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at TodotxtTouch.WindowsPhone.MainPivot.StartSync()
   at TodotxtTouch.WindowsPhone.MainPivot.SyncButtonClick(Object sender, EventArgs e)
   at Microsoft.Phone.Shell.ApplicationBarItemContainer.FireEventHandler(EventHandler handler, Object sender, EventArgs args)
   at Microsoft.Phone.Shell.ApplicationBarIconButtonContainer.ClickEvent()
   at Microsoft.Phone.Shell.ApplicationBar.OnCommand(UInt32 idCommand, Boolean isButton)
   at Microsoft.Phone.Shell.Interop.NativeCallbackInteropWrapper.OnCommand(UInt32 idCommand, Boolean isButton)

**Comment by hartez** [comment]
This method is now completely different with the new libraries, so whatever was causing this it'll be different now.
